apiVersion: v1
kind: Namespace
metadata:
  name: fms-app
  labels:
    name: fms-app

# Create the Pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fms-deploy
  namespace: fms-app
  labels:
    app: fms-ge
spec: # for deployment
  replicas: 1
  selector:
    matchLabels:
      app: fms-ge
  template:
    metadata:
      labels:
        app: fms-ge
    spec: # for pod
      containers:
      - name: fms-ge
        image: 1017860556361/fms_ge:v0.0.0
        resources: 
          limits:
            memory: "512Mi"  
            cpu: "300m"
          requests:                   # request memory can't greater than limits memory
            memory: "256Mi"  
            cpu: "200m"
        ports:
         - containerPort: 9090 


# Create the Internal Service  
# '---' by this syntex can create multile documants in yaml fle 

---    
apiVersion: v1
kind: Service
metadata:
  name: fms-ge-svc
  namespace: fms-app
spec: # for deployment
  selector:
      app: fms-ge
  type: LoadBalancer    
  ports:
     - protocol: TCP
       port: 9090
       targetPort: 9090